const cells = [
  ['出发','🚩','home'],['守护家人','🤝','safe'],['刷单陷阱','⚠️','risk','brushing'],['反诈课堂','📚','knowledge','knowledge'],['社区宣传','📣','service'],['客服退款','💬','risk','refund'],['安全通行','🌿','safe'],['网络交友','💔','risk','romance'],['热线守护','☎️','service'],['验证码','🔐','knowledge','knowledge'],['投资理财','📈','risk','investment'],['邻里提醒','🏘️','service'],['安全通行','🌿','safe'],['法治驿站','⚖️','service'],['冒充公检法','⚖️','risk','police'],['反诈课堂','📚','knowledge','knowledge'],['青年志愿','❤️','service'],['钓鱼链接','🔗','risk','phishing'],['安全通行','🌿','safe'],['预警劝阻','🛡️','service'],['保护密码','🔒','knowledge','knowledge'],['虚假快递','📦','risk','delivery'],['群防群治','👥','service'],['安全通行','🌿','safe'],['屏幕共享','🖥️','risk','screen'],['反诈课堂','📚','knowledge','knowledge'],['守护社区','🏠','service'],['平安终点','🏆','finish']
];
const positions = [[1,1],[1,2],[1,3],[1,4],[1,5],[1,6],[1,7],[2,7],[3,7],[4,7],[5,7],[5,6],[5,5],[5,4],[5,3],[5,2],[5,1],[4,1],[3,1],[2,1],[2,2],[2,3],[2,4],[2,5],[2,6],[3,6],[4,6],[4,5]];
const scenarios = {
  refund:{title:'警惕“客服退款”骗局',lines:[['陌生客服','您的商品有质量问题，可获三倍退款。'],['陌生客服','请下载退款 APP，并打开屏幕共享完成操作。']],clues:['陌生 APP','屏幕共享','高额退款'],choices:['马上下载 APP 领取赔偿','挂断后从官方订单页联系平台客服','把验证码读给对方'],correct:1,tip:'正规客服不会要求下载陌生软件、开启屏幕共享或索要验证码。'},
  brushing:{title:'警惕“刷单返利”骗局',lines:[['兼职群管理员','第一单返现 30 元，完成任务就能轻松赚钱。'],['兼职群管理员','先垫付 500 元，本金和佣金立刻到账。']],clues:['先垫资','高返现','兼职群'],choices:['先小额试一单','拒绝垫资返利并保留证据举报','向亲友借钱完成任务'],correct:1,tip:'所有要求先垫资的刷单返利，都是诈骗高发套路。'},
  police:{title:'警惕“冒充公检法”骗局',lines:[['办案人员','你涉嫌洗钱，请把资金转入安全账户接受审查。'],['办案人员','案件保密，不能告诉任何人。']],clues:['安全账户','电话办案','要求保密'],choices:['转入安全账户自证清白','挂断后拨打 110 或到公安机关核实','提供银行卡密码'],correct:1,tip:'公检法机关不会电话办案，更不存在所谓安全账户。'},
  investment:{title:'警惕“高收益投资”骗局',lines:[['投资老师','内部消息，这个项目保证翻倍，名额马上截止。']],clues:['内幕消息','保证收益','催促投资'],choices:['贷款加仓抓住机会','拒绝诱惑，只通过正规持牌渠道投资','跟着群里的老师开户'],correct:1,tip:'保本高收益、内幕消息和限时催促都是常见诱饵。'},
  romance:{title:'警惕“网络交友”骗局',lines:[['网络恋人','家人急需手术费，只有你能帮我。别告诉别人。']],clues:['未见面借钱','情感绑架','要求保密'],choices:['立即转账帮助恋人','不转账，核实身份并向亲友求助判断','发送身份证证明信任'],correct:1,tip:'素未谋面的“恋人”以急事借钱，应第一时间提高警惕。'},
  phishing:{title:'警惕“钓鱼链接”骗局',lines:[['短信通知','您的社保卡已停用，请于 24 小时内点击链接验证。']],clues:['陌生短链','制造恐慌','索要信息'],choices:['点击链接填写资料','不点链接，通过官方渠道查询','转发给家人一起办理'],correct:1,tip:'政务服务不会用陌生短链索取银行卡或验证码。'},
  delivery:{title:'警惕“快递赔付”骗局',lines:[['快递客服','您的快递丢失，可赔付 300 元，请加微信办理。'],['快递客服','需先转账认证，赔款才能到账。']],clues:['脱离平台','先转账','添加私信'],choices:['添加微信办理赔付','从订单内联系官方客服核验','先转账认证'],correct:1,tip:'快递理赔必须从购物订单或官方客服入口办理。'},
  screen:{title:'警惕“屏幕共享”骗局',lines:[['贷款专员','打开屏幕共享，把收到的验证码读给我，我远程帮你操作。']],clues:['屏幕共享','索要验证码','远程操作'],choices:['开启共享方便操作','立即拒绝并退出通话','把手机交给对方控制'],correct:1,tip:'屏幕共享会暴露验证码和账户信息，陌生人要求时必须拒绝。'},
  knowledge:{title:'反诈知识加油站',lines:[['反诈志愿者','验证码是账户安全的最后一道门，任何人索要都不能给。']],clues:['96110','官方核验','保护账户'],choices:['96110 来电直接挂断','及时接听，按民警提示核实','把号码拉黑继续转账'],correct:1,tip:'96110 是全国预警劝阻专线，请及时接听并配合核实。'}
};
const players = [
  {name:'红队 · 学生先锋',color:'red',label:'红',role:'学生先锋',tokens:[-1,-1,-1,-1],score:0,correct:0,services:0},
  {name:'蓝队 · 志愿网格员',color:'blue',label:'蓝',role:'志愿网格员',tokens:[-1,-1,-1,-1],score:0,correct:0,services:0}
];
let current = 0, dice = 0, rolling = false, waitingForToken = false, round = 1, selectedToken = null, pendingScenario = false;
const $ = id => document.querySelector(id);
const board = $('#board'), rollButton = $('#rollButton'), diceValue = $('#diceValue'), rollStatus = $('#rollStatus'), turnHint = $('#turnHint'), tokenChoices = $('#tokenChoices'), modalBackdrop = $('#modalBackdrop'), dialogue = $('#dialogue'), clueArea = $('#clueArea'), choiceArea = $('#choiceArea'), toast = $('#toast');

function totalScore(){return players.reduce((sum,player)=>sum+player.score,0)}
function saveProfile(){const old=JSON.parse(localStorage.getItem('antiFraudProfile')||'{"score":0,"badges":0}');const next={score:old.score+totalScore(),badges:old.badges+(players.some(p=>p.correct>=2)?1:0)};localStorage.setItem('antiFraudProfile',JSON.stringify(next));$('#savedScore').textContent=next.score;$('#savedBadges').textContent=next.badges}
function loadProfile(){const saved=JSON.parse(localStorage.getItem('antiFraudProfile')||'{"score":0,"badges":0}');$('#savedScore').textContent=saved.score;$('#savedBadges').textContent=saved.badges}
function buildBoard(){board.replaceChildren();const map=new Map(positions.map((position,index)=>[position.join('-'),index]));for(let row=1;row<=5;row++)for(let col=1;col<=7;col++){const index=map.get(`${row}-${col}`);if(index===undefined)continue;const [name,icon,type]=cells[index];const cell=document.createElement('div');cell.className=`cell ${type}`;cell.dataset.index=index;cell.style.gridArea=`${row} / ${col}`;cell.innerHTML=`<small class="cell-number">${index+1}</small><span class="cell-icon">${icon}</span><span class="cell-name">${name}</span>`;board.append(cell)}renderTokens()}
function renderTokens(){board.querySelectorAll('.token').forEach(token=>token.remove());players.forEach((player,playerIndex)=>player.tokens.forEach((position,tokenIndex)=>{if(position<0)return;const target=board.querySelector(`[data-index="${position}"]`);if(!target)return;const token=document.createElement('button');token.className=`token ${player.color}${selectedToken===tokenIndex&&playerIndex===current?' selected':''}`;token.style.left=`${3+(tokenIndex%2)*25}%`;token.style.top=`${35+Math.floor(tokenIndex/2)*28}%`;token.textContent=player.label;token.title=`${player.name} 第 ${tokenIndex+1} 枚棋子`;token.addEventListener('click',()=>moveToken(tokenIndex));target.append(token)}))}
function renderControls(){const player=players[current];$('#currentPlayer').textContent=player.name;$('#turnScore').textContent=`${player.score} 分`;$('#turnCard .turn-dot').className=`turn-dot ${player.color}`;$('#gameScore').textContent=totalScore();$('#roundNumber').textContent=round;tokenChoices.replaceChildren();player.tokens.forEach((position,index)=>{const button=document.createElement('button');button.className=`token-choice ${player.color}`;button.type='button';button.textContent=position===-1?`棋子 ${index+1} · 基地`:position===cells.length-1?`棋子 ${index+1} · 到达`:`棋子 ${index+1} · ${position+1} 格`;button.disabled=!waitingForToken||!canMove(position);button.addEventListener('click',()=>moveToken(index));tokenChoices.append(button)});const mission=player.color==='red'?['守护宿舍群','本局答对 2 道情景题，提醒同学不轻信陌生链接。']:['走进社区宣传','完成 2 次治理行动，把防诈知识带给身边居民。'];$('#missionTitle').textContent=mission[0];$('#missionText').textContent=mission[1]}
function canMove(position){return position===-1?dice===6:position<cells.length-1}
function showToast(message){toast.textContent=message;toast.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>toast.classList.remove('show'),2300)}
function roll(){if(rolling||waitingForToken)return;rolling=true;rollButton.disabled=true;rollButton.classList.add('rolling');turnHint.textContent='骰子正在决定你的行动…';setTimeout(()=>{dice=Math.floor(Math.random()*6)+1;diceValue.textContent=dice;rollButton.classList.remove('rolling');rolling=false;const movable=players[current].tokens.some(canMove);if(!movable){rollStatus.textContent=`掷出 ${dice} 点，没有可移动棋子`;switchTurn();return}waitingForToken=true;rollStatus.textContent=`掷出 ${dice} 点，请选择棋子`;turnHint.textContent=dice===6?'可以让基地棋子起飞，掷出 6 点还可再投一次。':'选择一枚棋子前进，风险格将触发情景任务。';renderControls()},520)}
function moveToken(index){if(!waitingForToken||!canMove(players[current].tokens[index]))return;selectedToken=index;const player=players[current];if(player.tokens[index]===-1){player.tokens[index]=0;showToast('棋子起飞！从反诈出发点进入社区。')}else player.tokens[index]=Math.min(cells.length-1,player.tokens[index]+dice);waitingForToken=false;renderTokens();renderControls();const landed=player.tokens[index];if(landed===cells.length-1){finishGame(player);return}const [,name,type,scenario]=cells[landed];rollStatus.textContent=`抵达「${name}」`;if(type==='service'){player.score+=8;player.services++;showToast('完成基层治理行动，获得 8 反诈值');afterLanding()}else if(scenario){setTimeout(()=>openScenario(scenario),300)}else{player.score+=2;showToast('安全通行，获得 2 反诈值');afterLanding()}}
function afterLanding(){renderControls();if(dice===6){rollButton.disabled=false;rollStatus.textContent='掷出 6 点，获得一次额外行动';turnHint.textContent='继续掷骰，为社区多一分守护！';return}switchTurn()}
function switchTurn(){current=(current+1)%players.length;round++;dice=0;waitingForToken=false;rollButton.disabled=false;rollStatus.textContent='等待行动';turnHint.textContent='掷出 6 点可让基地棋子起飞。';renderControls()}
function openScenario(key){const scenario=scenarios[key];pendingScenario=true;$('#modalTag').textContent=key==='knowledge'?'反诈知识加油站':'情景模拟 · 角色扮演';$('#modalTitle').textContent=scenario.title;dialogue.replaceChildren();scenario.lines.forEach(([speaker,text])=>{const bubble=document.createElement('div');bubble.className='bubble';bubble.innerHTML=`<span class="speaker">${speaker}</span>${text}`;dialogue.append(bubble)});clueArea.innerHTML='<p>请找出诈骗线索（点击至少 2 个）</p><div class="clue-list"></div>';const clueList=clueArea.querySelector('.clue-list');scenario.clues.forEach(text=>{const clue=document.createElement('button');clue.className='clue';clue.type='button';clue.textContent=text;clue.addEventListener('click',()=>clue.classList.toggle('active'));clueList.append(clue)});choiceArea.innerHTML=`<p>面对这个情境，你会怎么做？</p><div class="choices"></div>`;const choices=choiceArea.querySelector('.choices');scenario.choices.forEach((text,index)=>{const choice=document.createElement('button');choice.className='choice';choice.type='button';choice.textContent=`${String.fromCharCode(65+index)}. ${text}`;choice.addEventListener('click',()=>answerScenario(index,scenario,choice));choices.append(choice)});$('#continueButton').hidden=false;modalBackdrop.hidden=false}
function answerScenario(answer,scenario,button){pendingScenario=false;const buttons=[...choiceArea.querySelectorAll('.choice')];buttons.forEach(item=>item.disabled=true);const found=clueArea.querySelectorAll('.clue.active').length;const player=players[current];if(answer===scenario.correct){button.classList.add('correct');const bonus=found>=2?15:10;player.score+=bonus;player.correct++;showToast(`识诈成功，获得 ${bonus} 反诈值！`);choiceArea.insertAdjacentHTML('beforeend',`<div class="scenario-result">${scenario.tip}${found>=2?' 你已找出关键诈骗线索！':''}</div>`)}else{button.classList.add('wrong');buttons[scenario.correct].classList.add('correct');showToast('复盘正确方法，下次一定能识破');choiceArea.insertAdjacentHTML('beforeend',`<div class="scenario-result">正确做法：${scenario.choices[scenario.correct]}。${scenario.tip}</div>`)}renderControls();afterLanding()}
function finishGame(player){player.score+=30;saveProfile();$('#modalTag').textContent='平安守护报告';$('#modalTitle').textContent=`${player.name} 抵达平安终点！`;dialogue.innerHTML=`<div class="bubble"><span class="speaker">本局复盘</span>反诈值：${player.score} 分<br>识诈成功：${player.correct} 次<br>基层治理行动：${player.services} 次</div>`;clueArea.innerHTML=`<p>获得勋章</p><div class="clue-list"><span class="clue active">${player.correct>=2?'反诈先锋':'社区守护者'}</span><span class="clue active">青春治理同行</span></div>`;choiceArea.innerHTML='<div class="scenario-result">把今天学到的防骗知识分享给家人、同学和社区居民，守护就会持续发生。</div>';$('#continueButton').textContent='再来一局';$('#continueButton').onclick=restart;modalBackdrop.hidden=false}
function restart(){players.forEach(player=>Object.assign(player,{tokens:[-1,-1,-1,-1],score:0,correct:0,services:0}));current=0;dice=0;round=1;rolling=false;waitingForToken=false;pendingScenario=false;selectedToken=null;$('#continueButton').textContent='继续游戏';$('#continueButton').onclick=closeModal;closeModal();buildBoard();renderControls();rollButton.disabled=false;diceValue.textContent='✦';rollStatus.textContent='等待行动';turnHint.textContent='掷出 6 点才能让基地棋子起飞';showToast('新对局开始，准备守护平安社区！')}
function closeModal(){modalBackdrop.hidden=true;if(pendingScenario){pendingScenario=false;afterLanding()}}
rollButton.addEventListener('click',roll);$('#restartButton').addEventListener('click',restart);$('#newGameButton').addEventListener('click',restart);$('#closeModal').addEventListener('click',closeModal);$('#continueButton').addEventListener('click',closeModal);modalBackdrop.addEventListener('click',event=>{if(event.target===modalBackdrop)closeModal()});$('#ruleButton').addEventListener('click',()=>{const scenario={title:'本地双人反诈飞行棋',lines:[['玩法说明','红蓝双方轮流掷骰，掷出 6 点可让基地棋子起飞，并获得一次额外行动。'],['教育目标','落在风险格时完成“找线索 + 做选择”；落在治理格可获得社区行动分。']],clues:['识别话术','核验信息','求助举报'],choices:['我已了解，开始行动'],correct:0,tip:'先让一枚棋子抵达终点的一方获胜。'};openScenarioFrom(scenario)});
function openScenarioFrom(scenario){$('#modalTag').textContent='玩法说明';$('#modalTitle').textContent=scenario.title;dialogue.innerHTML=scenario.lines.map(line=>`<div class="bubble"><span class="speaker">${line[0]}</span>${line[1]}</div>`).join('');clueArea.innerHTML='<p>游戏目标</p><div class="clue-list"><span class="clue active">识诈</span><span class="clue active">防诈</span><span class="clue active">反诈</span></div>';choiceArea.innerHTML='';$('#continueButton').textContent='进入游戏';$('#continueButton').onclick=closeModal;modalBackdrop.hidden=false}
loadProfile();buildBoard();renderControls();
