const maps=[{title:'彩虹校园：守护同学群',goal:'收集 3 颗安全星星，就能点亮校园防护罩。',mission:'帮同学识破陌生链接',events:['link','refund','quiz']},{title:'阳光社区：守护爷爷奶奶',goal:'完成 2 次守护行动，点亮社区的平安灯。',mission:'教会家人核验陌生电话',events:['refund','delivery','quiz']},{title:'网络星球：打败骗局怪',goal:'找到 3 条关键线索，让骗局怪无处藏身。',mission:'识破屏幕共享小把戏',events:['screen','link','quiz']}];
const heroes={
  red:{name:'橙小盾队长',short:'红盾',speech:'“看到可疑消息，先翻开防诈指南！”',image:'assets/characters/mascot-red.png'},
  blue:{name:'蜜桔小法',short:'小法',speech:'“先学法、再识骗，关键一步要核验！”',image:'assets/characters/mascot-blue.png'},
  green:{name:'柿蒂阿婆',short:'阿婆',speech:'“不贪小便宜，陌生转账先问清！”',image:'assets/characters/mascot-green.png'},
  purple:{name:'桃桃普法员',short:'桃桃',speech:'“验证码是秘密，谁来索要都不给！”',image:'assets/characters/mascot-purple.png'}
};
const pieceTeams=['red','blue','green','purple'];
const cells=[['起飞站','🚩','home'],['安全草地','🌿','safe'],['神秘宝箱','🎁','chest'],['链接迷雾','⚠️','risk','link'],['线索站','🔎','clue','quiz'],['守护同学','🤝','help'],['安全草地','🌿','safe'],['退款怪','👾','risk','refund'],['神秘宝箱','🎁','chest'],['安全电话亭','☎️','help'],['快递迷雾','📦','risk','delivery'],['安全草地','🌿','safe'],['星星补给','⭐','chest'],['线索站','🔎','clue','quiz'],['屏幕共享怪','🖥️','risk','screen'],['守护家人','🏠','help'],['安全草地','🌿','safe'],['链接迷雾','🔗','risk','link'],['神秘宝箱','🎁','chest'],['小喇叭站','📣','help'],['线索站','🔎','clue','quiz'],['快递迷雾','📦','risk','delivery'],['安全草地','🌿','safe'],['平安终点','🏆','finish']];
const positions=[[1,1],[1,2],[1,3],[1,4],[1,5],[1,6],[1,7],[2,7],[3,7],[4,7],[5,7],[5,6],[5,5],[5,4],[5,3],[5,2],[5,1],[4,1],[3,1],[2,1],[2,2],[2,3],[2,4],[2,5]];
const stories={link:{title:'链接迷雾',lines:[['陌生消息','“你的游戏皮肤免费领，快点这个链接！”']],clues:['陌生链接','免费诱惑','催你立刻点'],answers:['马上点开领取','不点陌生链接，问家长或老师','把链接发到群里'],correct:1,tip:'不认识的人发来的链接，先不点，再找大人一起看看。'},refund:{title:'退款怪来电话',lines:[['陌生客服','“你的快递丢了，下载 APP 就能赔 300 元。”'],['陌生客服','“快打开屏幕共享，我帮你操作。”']],clues:['下载陌生 APP','屏幕共享','主动赔钱'],answers:['按对方说的下载 APP','挂断后从购物订单找官方客服','把验证码念给对方'],correct:1,tip:'正规客服不会让你下载陌生 APP、共享屏幕或念验证码。'},delivery:{title:'快递小陷阱',lines:[['陌生客服','“先转一元认证，才能拿到快递赔款。”']],clues:['先转账','私下联系','小额试探'],answers:['先转一元试试看','不转账，从官方订单核实','借爸爸妈妈手机转'],correct:1,tip:'任何“先转账再赔付”都是陷阱，要从官方订单里核验。'},screen:{title:'屏幕共享怪',lines:[['贷款专员','“打开屏幕共享，把验证码告诉我，我来帮你。”']],clues:['屏幕共享','验证码','远程操作'],answers:['打开共享让对方帮忙','拒绝并告诉家长','把验证码读出来'],correct:1,tip:'屏幕共享会让陌生人看到验证码和账户信息，必须拒绝。'},quiz:{title:'安全小问答',lines:[['橙小盾队长','“96110 来电时，我们应该怎么做？”']],clues:['官方预警','及时接听','核实情况'],answers:['害怕，马上挂断','及时接听，按民警提示核实','把号码拉黑'],correct:1,tip:'96110 是全国预警劝阻专线，接到电话请及时接听。'}};
const state={hero:'red',tokens:[-1,-1,-1,-1],dice:0,rolling:false,waiting:false,stars:0,clues:0,map:0,tools:{shield:1,magnifier:1,horn:0},pending:false};const $=id=>document.querySelector(id);const board=$('#board'),toast=$('#toast');
function buildBoard(){board.replaceChildren();const pos=new Map(positions.map((p,i)=>[p.join('-'),i]));for(let r=1;r<=5;r++)for(let c=1;c<=7;c++){const i=pos.get(`${r}-${c}`);if(i===undefined)continue;const [name,icon,type]=cells[i],el=document.createElement('div');el.className=`cell ${type}`;el.dataset.index=i;el.style.gridArea=`${r}/${c}`;el.innerHTML=`<small>${i+1}</small><span>${icon}</span><b>${name}</b>`;board.append(el)}renderPlanes()}
function renderPlanes(){board.querySelectorAll('.plane').forEach(el=>el.remove());state.tokens.forEach((position,index)=>{if(position<0)return;const hero=heroes[pieceTeams[index]],target=board.querySelector(`[data-index="${position}"]`),plane=document.createElement('button'),img=document.createElement('img');plane.className=`plane team-${pieceTeams[index]}`;plane.style.left=`${3+(index%2)*46}%`;plane.style.top=`${4+Math.floor(index/2)*45}%`;plane.type='button';plane.title=`移动${hero.name}`;plane.setAttribute('aria-label',`移动${hero.name}`);img.src=hero.image;img.alt='';plane.append(img);plane.addEventListener('click',()=>move(index));target.append(plane)})}
function render(){const hero=heroes[state.hero];$('#mascotFace').src=hero.image;$('#mascotFace').alt=`${hero.name}文创玩偶`;$('#mascotName').textContent=hero.name;$('#mascotSpeech').textContent=hero.speech;$('#playerEmoji').src=hero.image;$('#playerName').textContent=hero.name;$('#starCount').textContent=state.stars;$('#mapTitle').textContent=maps[state.map].title;$('#mapGoal').textContent=maps[state.map].goal;$('#missionTitle').textContent=maps[state.map].mission;$('#missionProgress').textContent=`${Math.min(state.clues,2)} / 2 次线索发现`;$('#starTrack').style.width=`${Math.min(100,state.stars/3*100)}%`;document.querySelectorAll('.map-tabs button').forEach((b,i)=>b.classList.toggle('active',i===state.map));['shield','magnifier','horn'].forEach(name=>$('#'+name+'Count').textContent=state.tools[name]);const choices=$('#planeChoices');choices.className='plane-choices';choices.replaceChildren();state.tokens.forEach((position,index)=>{const hero=heroes[pieceTeams[index]],b=document.createElement('button'),img=document.createElement('img'),label=document.createElement('span');b.className=`plane-choice team-${pieceTeams[index]}`;img.src=hero.image;img.alt='';label.textContent=position<0?`${hero.short} · 机场`:position===cells.length-1?`${hero.short} · 到达`:`${hero.short} · 第 ${position+1} 格`;b.append(img,label);b.disabled=!state.waiting||!canMove(position);b.addEventListener('click',()=>move(index));choices.append(b)});renderStickers();renderPlanes()}
function canMove(position){return position===-1?state.dice===6:position<cells.length-1&&position+state.dice<=cells.length-1}function toastMessage(text){toast.textContent=text;toast.classList.add('show');clearTimeout(window.t);window.t=setTimeout(()=>toast.classList.remove('show'),2200)}
function roll(){if(state.rolling||state.waiting)return;state.rolling=true;$('#rollButton').disabled=true;$('#rollButton').classList.add('rolling');$('#turnHint').textContent='呼呼呼，骰子转起来啦！';setTimeout(()=>{state.dice=Math.floor(Math.random()*6)+1;$('#diceValue').textContent=state.dice;$('#rollButton').classList.remove('rolling');state.rolling=false;if(!state.tokens.some(canMove)){toastMessage('这次没有可移动的反诈伙伴，下一次加油！');endTurn();return}state.waiting=true;$('#rollStatus').textContent=`掷出 ${state.dice} 点，选一位反诈伙伴吧！`;$('#turnHint').textContent=state.dice===6?'太棒了！可以从反诈基地出发，还能再掷一次。':'选一位反诈伙伴，向安全星球出发！';render()},500)}
function move(index){if(!state.waiting||!canMove(state.tokens[index]))return;if(state.tokens[index]===-1){state.tokens[index]=0;toastMessage(`${heroes[pieceTeams[index]].name}出发！`)}else state.tokens[index]+=state.dice;state.waiting=false;const landed=state.tokens[index];render();if(landed===cells.length-1){win();return}const [,name,type,event]=cells[landed];$('#rollStatus').textContent=`来到「${name}」`;if(type==='chest')openChest();else if(type==='help'){const bonus=state.tools.horn?4:2;if(state.tools.horn)state.tools.horn--;state.stars+=bonus;toastMessage(`你帮助了大家，获得 ${bonus} 颗安全星！`);afterMove()}else if(event)setTimeout(()=>openStory(event),250);else{state.stars++;toastMessage('安全通行，获得 1 颗安全星！');afterMove()}}
function afterMove(){save();render();if(state.dice===6){$('#rollButton').disabled=false;$('#rollStatus').textContent='掷出 6 点，再来一次！';return}endTurn()}function endTurn(){state.waiting=false;$('#rollButton').disabled=false;$('#rollStatus').textContent='准备下一次冒险';$('#turnHint').textContent='掷出 6 点，让一位反诈伙伴出发！';render()}
function openChest(){const gifts=[['🛡️','得到护盾！答错时可以保护一次。','shield'],['🔍','得到放大镜！可以点亮一条线索。','magnifier'],['📣','得到小喇叭！下一次帮助站奖励翻倍。','horn'],['⭐','发现安全星！','stars']];const gift=gifts[Math.floor(Math.random()*gifts.length)];if(gift[2]==='stars')state.stars+=3;else state.tools[gift[2]]++;modal('惊喜宝箱！',`<div class="result">${gift[0]} ${gift[1]}</div>`,'宝箱发现');afterMove()}
function openStory(key){state.pending=true;const story=stories[key];$('#modalTag').textContent='线索挑战';$('#modalTitle').textContent=story.title;$('#dialogue').innerHTML=story.lines.map(line=>`<div class="bubble"><b>${line[0]}</b>${line[1]}</div>`).join('');$('#clueBox').innerHTML='<p>点一点，找出可疑线索</p><div class="clue-list"></div>';const list=$('#clueBox .clue-list');story.clues.forEach(text=>{const b=document.createElement('button');b.className='clue';b.textContent=text;b.addEventListener('click',()=>b.classList.toggle('active'));list.append(b)});const answers=$('#answers');answers.replaceChildren();story.answers.forEach((text,i)=>{const b=document.createElement('button');b.className='answer';b.textContent=`${String.fromCharCode(65+i)}. ${text}`;b.addEventListener('click',()=>answer(i,story,b));answers.append(b)});$('#resultBox').innerHTML='';$('#continueButton').textContent='继续冒险';$('#modalBackdrop').hidden=false}
function answer(index,story,button){if(!state.pending)return;state.pending=false;const found=$('#clueBox').querySelectorAll('.active').length;[...$('#answers').children].forEach(b=>b.disabled=true);if(index===story.correct){button.classList.add('correct');state.stars+=found>=2?3:2;state.clues++;$('#resultBox').innerHTML=`<div class="result">太棒了！${story.tip}${found>=2?' 你还找到了关键线索！':''}</div>`;toastMessage('答对啦，安全星飞进背包！')}else if(state.tools.shield){state.tools.shield--;button.classList.add('wrong');$('#resultBox').innerHTML=`<div class="result">护盾保护了你一次！正确答案是：${story.answers[story.correct]}。${story.tip}</div>`;toastMessage('护盾闪闪发光，保护成功！')}else{$('#answers').children[story.correct].classList.add('correct');button.classList.add('wrong');$('#resultBox').innerHTML=`<div class="result">再记一次：${story.tip}</div>`;toastMessage('没关系，记住方法就是进步！')}afterMove()}
function modal(title,html,tag){state.pending=false;$('#modalTag').textContent=tag;$('#modalTitle').textContent=title;$('#dialogue').innerHTML=html;$('#clueBox').innerHTML='';$('#answers').innerHTML='';$('#resultBox').innerHTML='';$('#continueButton').textContent='继续冒险';$('#modalBackdrop').hidden=false}function closeModal(){if(state.pending){state.pending=false;afterMove()}$('#modalBackdrop').hidden=true}
function win(){state.stars+=5;const next=Math.min(2,state.map+1);save();modal('平安终点到达！',`<div class="result">🌈 你点亮了「${maps[state.map].title}」！获得 5 颗安全星和一枚勇敢贴纸。${next!==state.map?' 下一站已经解锁啦！':''}</div>`,'冒险成功');state.map=next;render()}
function renderStickers(){const all=[['🌟','安全新手',state.stars>=3],['🔎','线索达人',state.clues>=2],['🤝','热心伙伴',state.stars>=8],['🏆','星球卫士',state.tokens.some(t=>t===cells.length-1)]];$('#stickers').innerHTML=all.map(s=>`<div class="sticker ${s[2]?'unlocked':''}"><span>${s[0]}</span>${s[1]}</div>`).join('')}
function save(){localStorage.setItem('antiFraudKids',JSON.stringify({stars:state.stars,clues:state.clues,map:state.map}))}function load(){try{Object.assign(state,JSON.parse(localStorage.getItem('antiFraudKids')||'{}'))}catch{}}
$('#rollButton').addEventListener('click',roll);$('#restartButton').addEventListener('click',()=>{state.tokens=[-1,-1,-1,-1];state.dice=0;state.waiting=false;$('#diceValue').textContent='✦';endTurn();toastMessage('新的巡逻开始啦！')});$('#helpButton').addEventListener('click',()=>modal('冒险小秘籍','<div class="result">① 掷出 6 点，反诈伙伴才能从基地出发。<br>② 看到 ⚠️ 或 🔎，认真找线索再选择。<br>③ 🎁 宝箱会送你安全道具。<br>④ 先让一位反诈伙伴抵达 🏆 就通关！</div>','怎么玩'));$('#closeModal').addEventListener('click',closeModal);$('#continueButton').addEventListener('click',closeModal);$('#modalBackdrop').addEventListener('click',e=>{if(e.target===$('#modalBackdrop'))closeModal()});$('#heroPicker').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;state.hero=b.dataset.hero;document.querySelectorAll('#heroPicker button').forEach(x=>x.classList.toggle('selected',x===b));render()});$('#mapTabs').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;state.map=Number(b.dataset.map);render();toastMessage(`欢迎来到${maps[state.map].title}！`)});$('#magnifierTool').addEventListener('click',()=>{if(!state.tools.magnifier)return toastMessage('放大镜已经用完啦！');const clue=$('#clueBox .clue:not(.active)');if(!clue)return toastMessage('遇到线索挑战时再使用放大镜吧！');clue.classList.add('active');state.tools.magnifier--;render();toastMessage('放大镜点亮了一条线索！')});load();buildBoard();render();
